-- Run once in Supabase Dashboard > SQL Editor after reviewing the generated asset paths.
-- Converts database-embedded Base64 product images into GitHub static assets.
begin;
update public.products set image = 'assets/supabase/phone-case-for-iphone-carton-dog-mt5uzfo9/01.jpg', images = '["assets/supabase/phone-case-for-iphone-carton-dog-mt5uzfo9/01.jpg","assets/supabase/phone-case-for-iphone-carton-dog-mt5uzfo9/02.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-carton-dog-mt5uzfo9';
update public.products set image = 'assets/supabase/1688-1046882782655/01.jpg', images = '["assets/supabase/1688-1046882782655/01.jpg","assets/1688/1046882782655/15.webp"]'::jsonb, updated_at = now() where id = '1688-1046882782655';
update public.products set image = 'assets/supabase/1688-1060304503811/01.jpg', images = '["assets/supabase/1688-1060304503811/01.jpg"]'::jsonb, updated_at = now() where id = '1688-1060304503811';
update public.products set image = 'assets/supabase/key-chain-afro-small-mt9rc4yc/01.jpg', images = '["assets/supabase/key-chain-afro-small-mt9rc4yc/01.jpg"]'::jsonb, updated_at = now() where id = 'key-chain-afro-small-mt9rc4yc';
update public.products set image = 'assets/supabase/magnetic-phone-holder-mt5uih2j/01.jpg', images = '["assets/supabase/magnetic-phone-holder-mt5uih2j/01.jpg","assets/supabase/magnetic-phone-holder-mt5uih2j/02.jpg","assets/supabase/magnetic-phone-holder-mt5uih2j/03.jpg","assets/supabase/magnetic-phone-holder-mt5uih2j/04.jpg","assets/supabase/magnetic-phone-holder-mt5uih2j/05.jpg"]'::jsonb, updated_at = now() where id = 'magnetic-phone-holder-mt5uih2j';
update public.products set image = 'assets/supabase/phone-case-for-iphone-blue-dog-mt5suui9/01.jpg', images = '["assets/supabase/phone-case-for-iphone-blue-dog-mt5suui9/01.jpg","assets/supabase/phone-case-for-iphone-blue-dog-mt5suui9/02.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-blue-dog-mt5suui9';
update public.products set image = 'assets/supabase/phone-case-for-iphone-dog-paint-mt5thmrl/01.jpg', images = '["assets/supabase/phone-case-for-iphone-dog-paint-mt5thmrl/01.jpg","assets/supabase/phone-case-for-iphone-dog-paint-mt5thmrl/02.jpg","assets/supabase/phone-case-for-iphone-dog-paint-mt5thmrl/03.jpg","assets/supabase/phone-case-for-iphone-dog-paint-mt5thmrl/04.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-dog-paint-mt5thmrl';
update public.products set image = 'assets/supabase/phone-case-for-iphone-money-mt5sky4t/01.jpg', images = '["assets/supabase/phone-case-for-iphone-money-mt5sky4t/01.jpg","assets/supabase/phone-case-for-iphone-money-mt5sky4t/02.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-money-mt5sky4t';
update public.products set image = 'assets/supabase/phone-case-for-iphone-pink-spot-mt5urz2t/01.jpg', images = '["assets/supabase/phone-case-for-iphone-pink-spot-mt5urz2t/01.jpg","assets/supabase/phone-case-for-iphone-pink-spot-mt5urz2t/02.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-pink-spot-mt5urz2t';
update public.products set image = 'assets/supabase/phone-case-for-iphone-soft-toy-mt5uvejs/01.jpg', images = '["assets/supabase/phone-case-for-iphone-soft-toy-mt5uvejs/01.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-soft-toy-mt5uvejs';
update public.products set image = 'assets/supabase/phone-case-for-iphone-twinkle-mt5spqia/01.jpg', images = '["assets/supabase/phone-case-for-iphone-twinkle-mt5spqia/01.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-twinkle-mt5spqia';
update public.products set image = 'assets/supabase/phone-case-for-iphone-zoo-with-chain-mt5t80d3/01.jpg', images = '["assets/supabase/phone-case-for-iphone-zoo-with-chain-mt5t80d3/01.jpg"]'::jsonb, updated_at = now() where id = 'phone-case-for-iphone-zoo-with-chain-mt5t80d3';
update public.products set image = 'assets/supabase/soft-toy-dinosaur-mt76718u/01.jpg', images = '["assets/supabase/soft-toy-dinosaur-mt76718u/01.jpg"]'::jsonb, updated_at = now() where id = 'soft-toy-dinosaur-mt76718u';
update public.products set image = 'assets/supabase/tyke-3-blind-box-mt5nxmsa/01.jpg', images = '["assets/supabase/tyke-3-blind-box-mt5nxmsa/01.jpg"]'::jsonb, updated_at = now() where id = 'tyke-3-blind-box-mt5nxmsa';
update public.products set image = 'assets/supabase/key-chain-mt28xcyq/01.jpg', images = '["assets/supabase/key-chain-mt28xcyq/01.jpg"]'::jsonb, updated_at = now() where id = 'key-chain-mt28xcyq';
update public.products set image = 'assets/supabase/key-chain-mt29jv3r/01.jpg', images = '["assets/supabase/key-chain-mt29jv3r/01.jpg"]'::jsonb, updated_at = now() where id = 'key-chain-mt29jv3r';
update public.products set image = 'assets/supabase/key-chain-avocado-mt2bkd87/01.jpg', images = '["assets/supabase/key-chain-avocado-mt2bkd87/01.jpg"]'::jsonb, updated_at = now() where id = 'key-chain-avocado-mt2bkd87';
commit;
